owner: tjo-space
repo: status

sites:
  # TJO.SPACE
  - name: tjo.space
    url: https://tjo.space
  - name: search.tjo.space
    url: https://search.tjo.space
  - name: yt.tjo.space
    url: https://yt.tjo.space/feed/trending
  - name: send.tjo.space
    url: https://send.tjo.space
  - name: media.tjo.space
    url: https://media.tjo.space
  - name: cloud.tjo.space
    url: https://cloud.tjo.space/status.php
  - name: chat.tjo.space
    url: https://chat.tjo.space
  - name: matrix.chat.tjo.space
    url: https://matrix.chat.tjo.space/health
  - name: webhook.chat.tjo.space
    url: https://webhook.chat.tjo.space
    expectedStatusCodes:
      - 404 # Not Found
  - name: id.tjo.space
    url: https://id.tjo.space
  - name: code.tjo.space
    url: https://code.tjo.space
  - name: rss.tjo.space
    url: https://rss.tjo.space
  - name: vault.tjo.space
    url: https://vault.tjo.space
  - name: mail.tjo.space SMTP
    check: "tcp-ping"
    url: mail.tjo.space
    port: 465
  - name: mail.tjo.space IMAP
    check: "tcp-ping"
    url: mail.tjo.space
    port: 993
  # TJO.CLOUD
  - name: any.ingress.tjo.cloud
    url: http://any.ingress.tjo.cloud:1337/healthz
  - name: monitor.tjo.cloud
    url: https://monitor.tjo.cloud
    maxRedirects: 4
  - name: prometheus.monitor.tjo.cloud
    url: https://prometheus.monitor.tjo.cloud
  - name: loki.monitor.tjo.cloud
    url: https://loki.monitor.tjo.cloud
  - name: http.otel.monitor.tjo.cloud
    url: https://http.otel.monitor.tjo.cloud
    expectedStatusCodes:
      - 401 # Unauthorized
  - name: grpc.otel.monitor.tjo.cloud
    url: https://grpc.otel.monitor.tjo.cloud
    expectedStatusCodes:
      - 415 # Invalid GRCP request
  - name: proxmox.tjo.cloud
    url: https://proxmox.tjo.cloud
  - name: postgresql.tjo.cloud
    url: https://postgresql.tjo.cloud

status-website:
  cname: status.tjo.space
  logoUrl: https://tjo.space/img/icon.svg
  faviconSvg: https://tjo.space/img/icon.svg
  name: status.tjo.space
  introTitle: "**status.tjo.space**, here you can see the status of all tjo.space services."
  introMessage: |
    You can report any issues by sending an email to hostmaster@tjo.space or by
    sending a message in #hello:tjo.space matrix room.
  navbar:
    - title: Home
      href: https://tjo.space
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
