owner: tjo-space
repo: status

sites:
  - name: media.tjo.space
    url: https://media.tjo.space
  - name: cloud.tjo.space
    url: https://cloud.tjo.space
  - name: chat.tjo.space
    url: https://chat.tjo.space
  - name: id.tjo.space
    url: https://id.tjo.space
  - name: code.tjo.space
    url: https://code.tjo.space
  - name: home.tjo.space
    url: https://home.tjo.space
  - name: ci.tjo.space
    url: https://ci.tjo.space
  - name: mail.tjo.space SMTP
    check: "tcp-ping"
    url: mail.tjo.space
    port: 465
  - name: mail.tjo.space IMAP
    check: "tcp-ping"
    url: mail.tjo.space
    port: 993

status-website:
  cname: status.tjo.space
  logoUrl: https://avatars.githubusercontent.com/u/1910649
  name: status.tjo.space
  introTitle: "**status.tjo.space**, here you can see the status of all tjo.space services."
  introMessage: You can report any issues [here](https://github.com/tjo-space/status/issues).
  navbar:
    - title: Home
      href: https://home.tjo.space
    - title: Status
      href: /
    - title: Report Issues
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
