owner: tjo-space
repo: status

sites:
  - name: tjo.space
    url: https://tjo.space
  - name: search.tjo.space
    url: https://search.tjo.space
  - name: yt.tjo.space
    url: https://yt.tjo.space/feed/trending
  - name: send.tjo.space
    url: https://send.tjo.space
  - name: media.tjo.space
    url: https://media.tjo.space
  - name: cloud.tjo.space
    url: https://cloud.tjo.space/status.php
  - name: chat.tjo.space
    url: https://chat.tjo.space
  - name: id.tjo.space
    url: https://id.tjo.space
  - name: code.tjo.space
    url: https://code.tjo.space
  - name: rss.tjo.space
    url: https://rss.tjo.space
  - name: vault.tjo.space
    url: https://vault.tjo.space
  - name: mail.tjo.space SMTP
    check: "tcp-ping"
    url: mail.tjo.space
    port: 465
  - name: mail.tjo.space IMAP
    check: "tcp-ping"
    url: mail.tjo.space
    port: 993

status-website:
  cname: status.tjo.space
  logoUrl: https://tjo.space/img/icon.svg
  faviconSvg: https://tjo.space/img/icon.svg
  name: status.tjo.space
  introTitle: "**status.tjo.space**, here you can see the status of all tjo.space services."
  introMessage: |
    You can report any issues by sending an email to hostmaster@tjo.space or by
    sending a message in #hello:tjo.space matrix room.
  navbar:
    - title: Home
      href: https://tjo.space
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
